MOVES_CPP_ARGS = [
    '-DB_EXPANDED_MOVE_NAMES=1',
    '-DB_BINDING_TURNS=9',
    '-DB_USE_FROSTBITE=0',
    '-DB_UPDATED_MOVE_FLAGS=9',
    '-DB_UPDATED_MOVE_DATA=9',
    '-DB_UPDATED_MOVE_TYPES=9',
    '-DB_UPROAR_TURNS=9',
    '-DB_BLIZZARD_HAIL=9',
    '-DB_GROWTH_STAT_RAISE=9',
    '-DB_HIDDEN_POWER_DMG=9',
    '-DADDITIONAL_EFFECTS(...)={__VA_ARGS__}',
]

